import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import { ngoService, NGO } from '../services/ngoService';
import api from '../services/api';

declare global {
  interface Window {
    Razorpay: any;
  }
}

type PaymentMethod = 'upi' | 'card' | 'netbanking' | 'qr' | 'razorpay';

const DonationPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const donationRequestId = searchParams.get('donationRequestId');
  const [ngo, setNgo] = useState<NGO | null>(null);
  const [loading, setLoading] = useState(true);
  const [showPaymentForm, setShowPaymentForm] = useState(false);
  const [amount, setAmount] = useState(500);
  const [donorName, setDonorName] = useState('');
  const [donorEmail, setDonorEmail] = useState('');
  const [donorPhone, setDonorPhone] = useState('');
  const [processing, setProcessing] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('upi');
  const [upiId, setUpiId] = useState('');
  const [cardNumber, setCardNumber] = useState('');
  const [expiryDate, setExpiryDate] = useState('');
  const [cvv, setCvv] = useState('');
  const [bankName, setBankName] = useState('');
  const [showReceipt, setShowReceipt] = useState(false);
  const [transactionId, setTransactionId] = useState('');

  const generateReceipt = () => {
    const txnId = `TXN${Date.now()}`;
    setTransactionId(txnId);
    return txnId;
  };

  const downloadReceipt = () => {
    const receiptContent = `
DONATION RECEIPT
================

Transaction ID: ${transactionId}
Date: ${new Date().toLocaleDateString('en-IN')}
Time: ${new Date().toLocaleTimeString('en-IN')}

DONOR DETAILS:
Name: ${donorName}
Email: ${donorEmail}
Phone: ${donorPhone}

DONATION DETAILS:
Amount: ₹${amount}
To: ${ngo?.name}
Cause: ${ngo?.cause}
Payment Method: ${paymentMethod.toUpperCase()}

NGO DETAILS:
Name: ${ngo?.name}
Email: ${ngo?.contact?.email}
Phone: ${ngo?.contact?.phone}
Address: ${ngo?.contact?.address}

Thank you for your generous donation!
This receipt is valid for tax exemption under Section 80G.

Generated by CONNECT NGO Platform
    `;

    const blob = new Blob([receiptContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `donation-receipt-${transactionId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  // Sample NGO data
  const sampleNGOs: NGO[] = [
    {
      _id: '1',
      name: 'Save Children India',
      description: 'Helping children across India with education and healthcare. We provide school supplies, medical care, and nutritious meals to children in need.',
      cause: 'Child Welfare',
      contact: { email: 'contact@savechildren.in', phone: '+91-9876543210', address: 'Mumbai, Maharashtra' },
      isVerified: true
    },
    {
      _id: '2', 
      name: 'Clean Water Initiative',
      description: 'Providing clean water access to rural communities across India. We build wells, install water purification systems, and educate communities about water safety.',
      cause: 'Water & Sanitation',
      contact: { email: 'info@cleanwater.in', phone: '+91-9876543211', address: 'Bangalore, Karnataka' },
      isVerified: false
    },
    {
      _id: '3',
      name: 'Education First India',
      description: 'Promoting education in underserved areas across India. We build schools, train teachers, and provide scholarships to deserving students.',
      cause: 'Education',
      contact: { email: 'hello@educationfirst.in', phone: '+91-9876543212', address: 'Delhi, India' },
      isVerified: true
    }
  ];

  useEffect(() => {
    fetchNGO();
  }, [id]);

  const fetchNGO = async () => {
    if (!id) {
      console.log('No NGO ID provided');
      return;
    }

    console.log('Fetching NGO with ID:', id);
    try {
      setLoading(true);
      const foundNGO = await ngoService.getNGOById(id);
      console.log('Found NGO:', foundNGO);
      if (foundNGO) {
        setNgo(foundNGO);
      } else {
        console.log('NGO not found, redirecting to browse');
        navigate('/browse');
      }
    } catch (error) {
      console.error('Error fetching NGO:', error);
      navigate('/browse');
    } finally {
      setLoading(false);
    }
  };

  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handleRazorpayPayment = async () => {
    try {
      // Load Razorpay script
      const scriptLoaded = await loadRazorpayScript();
      if (!scriptLoaded) {
        throw new Error('Razorpay SDK failed to load');
      }

      // Create Razorpay order
      const orderResponse = await api.post('/payments/razorpay/create-order', {
        ngoId: ngo?._id,
        amount: amount,
        message: `Donation to ${ngo?.name}`,
        anonymous: false
      });

      const { orderId, amount: orderAmount, currency, donationId, key } = orderResponse.data;

      // Configure Razorpay options
      const options = {
        key: key,
        amount: orderAmount,
        currency: currency,
        name: 'CONNECT NGO',
        description: `Donation to ${ngo?.name}`,
        order_id: orderId,
        handler: async (response: any) => {
          try {
            // Verify payment on backend
            const verifyResponse = await api.post('/payments/razorpay/verify-payment', {
              razorpay_order_id: response.razorpay_order_id,
              razorpay_payment_id: response.razorpay_payment_id,
              razorpay_signature: response.razorpay_signature,
              donationId: donationId
            });

            if (verifyResponse.data.success) {
              const txnId = response.razorpay_payment_id;
              setTransactionId(txnId);
              setShowReceipt(true);
            } else {
              alert('Payment verification failed');
            }
          } catch (verifyError) {
            console.error('Payment verification error:', verifyError);
            alert('Payment verification failed');
          } finally {
            setProcessing(false);
          }
        },
        prefill: {
          name: donorName,
          email: donorEmail,
          contact: donorPhone
        },
        theme: {
          color: '#3B82F6'
        },
        modal: {
          ondismiss: () => {
            setProcessing(false);
          }
        }
      };

      // Open Razorpay checkout
      const razorpay = new window.Razorpay(options);
      razorpay.open();

    } catch (error: any) {
      console.error('Razorpay payment error:', error);
      alert(error.response?.data?.message || 'Payment failed. Please try again.');
      setProcessing(false);
    }
  };

  const handleDonation = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!ngo) return;

    setProcessing(true);
    
    try {
      // Handle Razorpay payment separately
      if (paymentMethod === 'razorpay') {
        await handleRazorpayPayment();
        return;
      }

      // Simulate payment processing based on method for other methods
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      const txnId = generateReceipt();
      
      // Save donation to backend database
      console.log('🔍 Checking authentication...');
      const token = localStorage.getItem('token');
      console.log('Token:', token);
      
      const paymentResponse = await api.post('/payments/create-donation', {
        ngoId: parseInt(ngo._id) || ngo._id,
        amount: amount,
        message: `Payment via ${paymentMethod}`,
        anonymous: false,
        ...(donationRequestId && { donationRequestId })
      });
      
      let paymentDetails = '';
      switch (paymentMethod) {
        case 'upi':
          paymentDetails = `UPI ID: ${upiId}`;
          break;
        case 'card':
          paymentDetails = `Card ending in ${cardNumber.slice(-4)}`;
          break;
        case 'netbanking':
          paymentDetails = `${bankName} Net Banking`;
          break;
        case 'qr':
          paymentDetails = 'QR Code Payment';
          break;
      }
      
      setShowReceipt(true);
      
    } catch (error: any) {
      console.error('Payment error:', error);
      console.error('Error response:', error.response?.data);
      console.error('Error status:', error.response?.status);
      alert(`❌ Payment failed: ${error.response?.data?.message || error.message || 'Please try again.'}`);
    } finally {
      setProcessing(false);
    }
  };

  const renderPaymentMethodForm = () => {
    switch (paymentMethod) {
      case 'razorpay':
        return (
          <div className="space-y-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <div className="flex items-center space-x-3">
                <div className="text-2xl">💎</div>
                <div>
                  <p className="text-sm font-medium text-blue-700">Razorpay Secure Payment</p>
                  <p className="text-xs text-blue-600">
                    Supports UPI, Cards, Net Banking, and Wallets
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-green-50 p-4 rounded-lg">
              <p className="text-sm text-green-700">
                ✅ Click "Donate Now" to proceed with secure Razorpay checkout
              </p>
            </div>
          </div>
        );

      case 'upi':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                UPI ID *
              </label>
              <input
                type="text"
                required
                value={upiId}
                onChange={(e) => setUpiId(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="yourname@paytm / yourname@gpay"
              />
            </div>
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-sm text-blue-700">
                💡 Enter your UPI ID (e.g., 9876543210@paytm, yourname@gpay)
              </p>
            </div>
          </div>
        );

      case 'card':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Card Number *
              </label>
              <input
                type="text"
                required
                value={cardNumber}
                onChange={(e) => setCardNumber(e.target.value.replace(/\D/g, '').slice(0, 16))}
                className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="1234 5678 9012 3456"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Expiry Date *
                </label>
                <input
                  type="text"
                  required
                  value={expiryDate}
                  onChange={(e) => setExpiryDate(e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="MM/YY"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  CVV *
                </label>
                <input
                  type="text"
                  required
                  value={cvv}
                  onChange={(e) => setCvv(e.target.value.replace(/\D/g, '').slice(0, 3))}
                  className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="123"
                />
              </div>
            </div>
          </div>
        );

      case 'netbanking':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Select Your Bank *
              </label>
              <select
                required
                value={bankName}
                onChange={(e) => setBankName(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Choose your bank</option>
                <option value="State Bank of India">State Bank of India</option>
                <option value="HDFC Bank">HDFC Bank</option>
                <option value="ICICI Bank">ICICI Bank</option>
                <option value="Axis Bank">Axis Bank</option>
                <option value="Punjab National Bank">Punjab National Bank</option>
                <option value="Bank of Baroda">Bank of Baroda</option>
                <option value="Canara Bank">Canara Bank</option>
                <option value="Union Bank">Union Bank</option>
              </select>
            </div>
            <div className="bg-yellow-50 p-4 rounded-lg">
              <p className="text-sm text-yellow-700">
                🏦 You will be redirected to your bank's secure login page
              </p>
            </div>
          </div>
        );

      case 'qr':
        return (
          <div className="space-y-4">
            <div className="text-center">
              <div className="bg-gray-100 p-8 rounded-lg inline-block">
                <div className="w-48 h-48 bg-white border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center">
                  <div className="text-center">
                    <div className="text-4xl mb-2">📱</div>
                    <p className="text-sm text-gray-600">QR Code</p>
                    <p className="text-xs text-gray-500">Scan with any UPI app</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-green-50 p-4 rounded-lg">
              <p className="text-sm text-green-700 text-center">
                📲 Scan this QR code with PhonePe, Google Pay, Paytm, or any UPI app
              </p>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading NGO details...</p>
        </div>
      </div>
    );
  }

  if (!ngo) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">NGO Not Found</h2>
          <p className="text-gray-600 mb-6">The NGO you're looking for doesn't exist.</p>
          <button
            onClick={() => navigate('/browse')}
            className="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700"
          >
            Browse NGOs
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {showReceipt ? (
          <div className="bg-white rounded-lg shadow-lg p-8 text-center">
            <div className="mb-6">
              <div className="text-6xl mb-4">🎉</div>
              <h2 className="text-3xl font-bold text-green-600 mb-2">Payment Successful!</h2>
              <p className="text-gray-600">Thank you for your generous donation</p>
            </div>

            <div className="bg-green-50 p-6 rounded-lg mb-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
                <div>
                  <p className="text-sm text-gray-600">Transaction ID</p>
                  <p className="font-semibold">{transactionId}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Amount</p>
                  <p className="font-semibold text-green-600">₹{amount}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Donor</p>
                  <p className="font-semibold">{donorName}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">NGO</p>
                  <p className="font-semibold">{ngo?.name}</p>
                </div>
              </div>
            </div>

            <div className="flex space-x-4 justify-center">
              <button
                onClick={downloadReceipt}
                className="bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700 font-semibold"
              >
                📄 Download Receipt
              </button>
              <button
                onClick={() => navigate('/browse')}
                className="border border-gray-300 text-gray-700 px-6 py-3 rounded-md hover:bg-gray-50"
              >
                ← Back to Browse
              </button>
            </div>

            <div className="mt-6 text-sm text-gray-500">
              <p>💡 Your receipt is valid for tax exemption under Section 80G</p>
              <p>A confirmation email has been sent to {donorEmail}</p>
            </div>
          </div>
        ) : !showPaymentForm ? (
          <div className="bg-white rounded-lg shadow-lg overflow-hidden">
            <div className="p-8">
              <div className="flex items-center justify-between mb-6">
                <h1 className="text-3xl font-bold text-gray-900">{ngo.name}</h1>
                {ngo.isVerified && (
                  <span className="bg-green-100 text-green-800 text-sm px-3 py-1 rounded-full">
                    ✓ Verified NGO
                  </span>
                )}
              </div>

              <div className="mb-6">
                <span className="inline-block bg-blue-100 text-blue-800 text-sm px-3 py-1 rounded-full">
                  {ngo.cause}
                </span>
              </div>

              <div className="prose max-w-none mb-8">
                <p className="text-gray-600 text-lg leading-relaxed">
                  {ngo.description}
                </p>
              </div>

              <div className="bg-gray-50 rounded-lg p-6 mb-8">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Contact Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <p className="text-sm text-gray-500">Email</p>
                    <p className="font-medium">{ngo.contact?.email || 'Not provided'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">Phone</p>
                    <p className="font-medium">{ngo.contact?.phone || 'Not provided'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">Address</p>
                    <p className="font-medium">{ngo.contact?.address || 'Not provided'}</p>
                  </div>
                </div>
              </div>

              <div className="flex space-x-4">
                <button
                  onClick={() => setShowPaymentForm(true)}
                  className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-700 transition-colors"
                >
                  💳 Donate Now
                </button>
                <button
                  onClick={() => navigate('/browse')}
                  className="border border-gray-300 text-gray-700 px-8 py-3 rounded-lg text-lg font-semibold hover:bg-gray-50 transition-colors"
                >
                  ← Back to Browse
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-lg shadow-lg p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">💝 Donate to {ngo.name}</h2>
            
            <form onSubmit={handleDonation} className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Donation Amount (₹)
                </label>
                <div className="flex space-x-4 mb-4">
                  {[500, 1000, 2500, 5000].map((preset) => (
                    <button
                      key={preset}
                      type="button"
                      onClick={() => setAmount(preset)}
                      className={`px-4 py-2 rounded-md transition-colors ${
                        amount === preset
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      ₹{preset}
                    </button>
                  ))}
                </div>
                <input
                  type="number"
                  min="1"
                  value={amount}
                  onChange={(e) => setAmount(parseInt(e.target.value) || 0)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter custom amount"
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Your Name *
                  </label>
                  <input
                    type="text"
                    required
                    value={donorName}
                    onChange={(e) => {
                      console.log('Name input changed:', e.target.value);
                      setDonorName(e.target.value);
                    }}
                    className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter your full name"
                    disabled={processing}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Phone Number *
                  </label>
                  <input
                    type="tel"
                    required
                    value={donorPhone}
                    onChange={(e) => {
                      console.log('Phone input changed:', e.target.value);
                      setDonorPhone(e.target.value);
                    }}
                    className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="+91 9876543210"
                    disabled={processing}
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email Address *
                </label>
                <input
                  type="email"
                  required
                  value={donorEmail}
                  onChange={(e) => {
                    console.log('Email input changed:', e.target.value);
                    setDonorEmail(e.target.value);
                  }}
                  className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter your email address"
                  disabled={processing}
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-4">
                  Payment Method *
                </label>
                <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
                  {[
                    { id: 'razorpay', name: 'Razorpay', icon: '💎', desc: 'Secure Gateway' },
                    { id: 'upi', name: 'UPI', icon: '📱', desc: 'PhonePe, GPay, Paytm' },
                    { id: 'card', name: 'Card', icon: '💳', desc: 'Debit/Credit Card' },
                    { id: 'netbanking', name: 'Net Banking', icon: '🏦', desc: 'Online Banking' },
                    { id: 'qr', name: 'QR Code', icon: '📲', desc: 'Scan & Pay' }
                  ].map((method) => (
                    <button
                      key={method.id}
                      type="button"
                      onClick={() => setPaymentMethod(method.id as PaymentMethod)}
                      className={`p-4 border-2 rounded-lg text-center transition-colors ${
                        paymentMethod === method.id
                          ? 'border-blue-500 bg-blue-50 text-blue-700'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      <div className="text-2xl mb-1">{method.icon}</div>
                      <div className="font-medium text-sm">{method.name}</div>
                      <div className="text-xs text-gray-500">{method.desc}</div>
                    </button>
                  ))}
                </div>

                {renderPaymentMethodForm()}
              </div>

              <div className="bg-blue-50 p-6 rounded-lg">
                <h4 className="font-semibold text-gray-900 mb-3">💰 Payment Summary</h4>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span>Amount:</span>
                    <span className="font-semibold text-blue-600">₹{amount}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>To:</span>
                    <span className="font-semibold">{ngo.name}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Cause:</span>
                    <span>{ngo.cause}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Payment Method:</span>
                    <span className="capitalize">{paymentMethod === 'qr' ? 'QR Code' : paymentMethod === 'netbanking' ? 'Net Banking' : paymentMethod.toUpperCase()}</span>
                  </div>
                </div>
              </div>

              <div className="flex space-x-4">
                <button
                  type="submit"
                  disabled={processing || amount <= 0 || !donorName || !donorEmail || !donorPhone}
                  className="flex-1 bg-green-600 text-white px-6 py-3 rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed font-semibold"
                >
                  {processing ? '⏳ Processing Payment...' : `🎯 Pay ₹${amount}`}
                </button>
                <button
                  type="button"
                  onClick={() => setShowPaymentForm(false)}
                  className="flex-1 border border-gray-300 text-gray-700 px-6 py-3 rounded-md hover:bg-gray-50"
                >
                  ← Cancel
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
};

export default DonationPage;
